<?php
/**
 * BillingApi
 * PHP version 5
 *
 * @category Class
 * @package  Liquid\Client
 * @author   http://github.com/liquidregistrar/liquid-php
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/liquidregistrar/liquid-php
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the liquid code generator program.
 * https://github.com/liquidregistrar/liquid-php
 * Do not edit the class manually.
 */

namespace Liquid\Client\Api;

use \Liquid\Client\Configuration;
use \Liquid\Client\ApiClient;
use \Liquid\Client\ApiException;
use \Liquid\Client\ObjectSerializer;

/**
 * BillingApi Class Doc Comment
 *
 * @category Class
 * @package  Liquid\Client
 * @author   http://github.com/liquidregistrar/liquid-php
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/liquidregistrar/liquid-php
 */
class BillingApi
{

    /**
     * API Client
     * @var \Liquid\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     * @param \Liquid\Client\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://api.liqu.id/v1');
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     * @return \Liquid\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     * @param \Liquid\Client\ApiClient $apiClient set the API client
     * @return BillingApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }


    /**
     * customerBalance
     *
     * retrieve a customer's balance
     *
     * @param int $customer_id Customer Id of the Customer whose Available Balance is to be fetched (required)
     * @return void
     * @throws \Liquid\Client\ApiException on non-2xx response
     */
    public function customerBalance($customer_id)
    {

        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling customerBalance');
        }

        // parse inputs
        $resourcePath = "/customers/{customer_id}/balance";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "GET";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());



        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customer_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }



        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } else if (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }

        // make the API Call
        try
        {
            list($response, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams
            );

            return array($response, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }

    }

    /**
     * allCustomerTransaction
     *
     * list all transactions of a customer
     *
     * @param int $customer_id Customer Id of the Customer (required)
     * @param int $limit Limit number of Transactions to be fetched. This should be a value between 10 to 100. (optional)
     * @param int $page_no Page number for which details are to be fetched (optional)
     * @param string $transaction_type Type of the Transactions. Possible values can be : domain, deposit, note, privacy_protect. (optional)
     * @param string $transaction_id Transaction Ids : 1,2,3,4. (optional)
     * @param string $date_start UNIX TimeStamp for listing of Transactions whose Creation Date is greater than date_start. Value can be yyyy-mm-dd. (optional)
     * @param string $date_end UNIX TimeStamp for listing of Transactions whose Creation Date is less than date_end. Value can be yyyy-mm-dd. (optional)
     * @param int $amount_range_start Lowest amount in the range of Transactions you intend to list (optional)
     * @param int $amount_range_end Highest amount in the range of Transactions you intend to list (optional)
     * @param string $description Description (optional)
     * @param bool $only_pending Show only pending transactions. can be filled with string true or false, 1 or 0 (optional)
     * @return void
     * @throws \Liquid\Client\ApiException on non-2xx response
     */
    public function allCustomerTransaction($customer_id, $limit=null, $page_no=null, $transaction_type=null, $transaction_id=null, $date_start=null, $date_end=null, $amount_range_start=null, $amount_range_end=null, $description=null, $only_pending=null)
    {

        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling allCustomerTransaction');
        }

        // parse inputs
        $resourcePath = "/customers/{customer_id}/transactions";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "GET";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());

        // query params
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }// query params
        if ($page_no !== null) {
            $queryParams['page_no'] = $this->apiClient->getSerializer()->toQueryValue($page_no);
        }// query params
        if ($transaction_type !== null) {
            $queryParams['transaction_type'] = $this->apiClient->getSerializer()->toQueryValue($transaction_type);
        }// query params
        if ($transaction_id !== null) {
            $queryParams['transaction_id'] = $this->apiClient->getSerializer()->toQueryValue($transaction_id);
        }// query params
        if ($date_start !== null) {
            $queryParams['date_start'] = $this->apiClient->getSerializer()->toQueryValue($date_start);
        }// query params
        if ($date_end !== null) {
            $queryParams['date_end'] = $this->apiClient->getSerializer()->toQueryValue($date_end);
        }// query params
        if ($amount_range_start !== null) {
            $queryParams['amount_range_start'] = $this->apiClient->getSerializer()->toQueryValue($amount_range_start);
        }// query params
        if ($amount_range_end !== null) {
            $queryParams['amount_range_end'] = $this->apiClient->getSerializer()->toQueryValue($amount_range_end);
        }// query params
        if ($description !== null) {
            $queryParams['description'] = $this->apiClient->getSerializer()->toQueryValue($description);
        }// query params
        if ($only_pending !== null) {
            $queryParams['only_pending'] = $this->apiClient->getSerializer()->toQueryValue($only_pending);
        }

        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customer_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }



        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } else if (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }

        // make the API Call
        try
        {
            list($response, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams
            );

            return array($response, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }

    }

    /**
     * cancelCustomerInvoice
     *
     * cancel a customer's pending invoice
     *
     * @param int $customer_id Customer Id of Customer (required)
     * @param int $transaction_id Transaction Ids of the Transactions which want to be canceled (required)
     * @return void
     * @throws \Liquid\Client\ApiException on non-2xx response
     */
    public function cancelCustomerInvoice($customer_id, $transaction_id)
    {

        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling cancelCustomerInvoice');
        }
        // verify the required parameter 'transaction_id' is set
        if ($transaction_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $transaction_id when calling cancelCustomerInvoice');
        }

        // parse inputs
        $resourcePath = "/customers/{customer_id}/transactions/cancel";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());



        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customer_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }
        // form params
        if ($transaction_id !== null) {
            $formParams['transaction_id'] = $this->apiClient->getSerializer()->toFormValue($transaction_id);
        }


        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } else if (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }

        // make the API Call
        try
        {
            list($response, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams
            );

            return array($response, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }

    }

    /**
     * addDebitCustomer
     *
     * add debit note to a customer
     *
     * @param int $customer_id Customer Id of Customer against whom Debit Note is to be added (required)
     * @param string $amount Amount of Debit Note (required)
     * @param string $description Description for the Debit Note (required)
     * @return void
     * @throws \Liquid\Client\ApiException on non-2xx response
     */
    public function addDebitCustomer($customer_id, $amount, $description)
    {

        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling addDebitCustomer');
        }
        // verify the required parameter 'amount' is set
        if ($amount === null) {
            throw new \InvalidArgumentException('Missing the required parameter $amount when calling addDebitCustomer');
        }
        // verify the required parameter 'description' is set
        if ($description === null) {
            throw new \InvalidArgumentException('Missing the required parameter $description when calling addDebitCustomer');
        }

        // parse inputs
        $resourcePath = "/customers/{customer_id}/transactions/debit_note";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());



        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customer_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }
        // form params
        if ($amount !== null) {
            $formParams['amount'] = $this->apiClient->getSerializer()->toFormValue($amount);
        }// form params
        if ($description !== null) {
            $formParams['description'] = $this->apiClient->getSerializer()->toFormValue($description);
        }


        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } else if (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }

        // make the API Call
        try
        {
            list($response, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams
            );

            return array($response, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }

    }

    /**
     * executeCustomerInvoice
     *
     * execute a customer's pending Orderonly
     *
     * @param int $customer_id Customer Id of Customer (required)
     * @param int $transaction_id Transaction Ids of the Transactions which want to be executed (required)
     * @param bool $cancel_invoice true or false, 1 or 0 (required)
     * @return void
     * @throws \Liquid\Client\ApiException on non-2xx response
     */
    public function executeCustomerInvoice($customer_id, $transaction_id, $cancel_invoice)
    {

        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling executeCustomerInvoice');
        }
        // verify the required parameter 'transaction_id' is set
        if ($transaction_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $transaction_id when calling executeCustomerInvoice');
        }
        // verify the required parameter 'cancel_invoice' is set
        if ($cancel_invoice === null) {
            throw new \InvalidArgumentException('Missing the required parameter $cancel_invoice when calling executeCustomerInvoice');
        }

        // parse inputs
        $resourcePath = "/customers/{customer_id}/transactions/execute";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());



        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customer_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }
        // form params
        if ($transaction_id !== null) {
            $formParams['transaction_id'] = $this->apiClient->getSerializer()->toFormValue($transaction_id);
        }// form params
        if ($cancel_invoice !== null) {
            $formParams['cancel_invoice'] = $this->apiClient->getSerializer()->toFormValue($cancel_invoice);
        }


        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } else if (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }

        // make the API Call
        try
        {
            list($response, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams
            );

            return array($response, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }

    }

    /**
     * addFundCustomer
     *
     * add fund to a customer
     *
     * @param int $customer_id Customer Id of the Customer in whose Debit Account these funds are to be added (required)
     * @param string $amount Amount to be added (required)
     * @param string $description Description for the Transaction (required)
     * @return void
     * @throws \Liquid\Client\ApiException on non-2xx response
     */
    public function addFundCustomer($customer_id, $amount, $description)
    {

        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling addFundCustomer');
        }
        // verify the required parameter 'amount' is set
        if ($amount === null) {
            throw new \InvalidArgumentException('Missing the required parameter $amount when calling addFundCustomer');
        }
        // verify the required parameter 'description' is set
        if ($description === null) {
            throw new \InvalidArgumentException('Missing the required parameter $description when calling addFundCustomer');
        }

        // parse inputs
        $resourcePath = "/customers/{customer_id}/transactions/fund";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());



        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customer_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }
        // form params
        if ($amount !== null) {
            $formParams['amount'] = $this->apiClient->getSerializer()->toFormValue($amount);
        }// form params
        if ($description !== null) {
            $formParams['description'] = $this->apiClient->getSerializer()->toFormValue($description);
        }


        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } else if (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }

        // make the API Call
        try
        {
            list($response, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams
            );

            return array($response, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }

    }

    /**
     * payCustomerInvoice
     *
     * pay a customer's transaction keep invoice
     *
     * @param int $customer_id Customer Id of Customer (required)
     * @param int $transaction_id Transaction Ids of the Transactions which want to be pay (required)
     * @param bool $subtract_balance Reduce customer balances string true or false (required)
     * @return void
     * @throws \Liquid\Client\ApiException on non-2xx response
     */
    public function payCustomerInvoice($customer_id, $transaction_id, $subtract_balance)
    {

        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling payCustomerInvoice');
        }
        // verify the required parameter 'transaction_id' is set
        if ($transaction_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $transaction_id when calling payCustomerInvoice');
        }
        // verify the required parameter 'subtract_balance' is set
        if ($subtract_balance === null) {
            throw new \InvalidArgumentException('Missing the required parameter $subtract_balance when calling payCustomerInvoice');
        }

        // parse inputs
        $resourcePath = "/customers/{customer_id}/transactions/pay";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());



        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customer_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }
        // form params
        if ($transaction_id !== null) {
            $formParams['transaction_id'] = $this->apiClient->getSerializer()->toFormValue($transaction_id);
        }// form params
        if ($subtract_balance !== null) {
            $formParams['subtract_balance'] = $this->apiClient->getSerializer()->toFormValue($subtract_balance);
        }


        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } else if (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }

        // make the API Call
        try
        {
            list($response, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams
            );

            return array($response, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }

    }

    /**
     * payAddOnly
     *
     * pay a customer's transaction add only
     *
     * @param int $customer_id Customer Id of Customer (required)
     * @param int $transaction_id Transaction Ids of the Transactions which want to be pay (required)
     * @return void
     * @throws \Liquid\Client\ApiException on non-2xx response
     */
    public function payAddOnly($customer_id, $transaction_id)
    {

        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling payAddOnly');
        }
        // verify the required parameter 'transaction_id' is set
        if ($transaction_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $transaction_id when calling payAddOnly');
        }

        // parse inputs
        $resourcePath = "/customers/{customer_id}/transactions/pay_add_only";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());



        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customer_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }
        // form params
        if ($transaction_id !== null) {
            $formParams['transaction_id'] = $this->apiClient->getSerializer()->toFormValue($transaction_id);
        }


        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } else if (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }

        // make the API Call
        try
        {
            list($response, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams
            );

            return array($response, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }

    }

    /**
     * customerTransaction
     *
     * retrieve a customer's transaction
     *
     * @param int $customer_id Customer Id of the Customer (required)
     * @param int $transaction_id Transaction Ids of the Transactions whose details are to be fetched (required)
     * @return void
     * @throws \Liquid\Client\ApiException on non-2xx response
     */
    public function customerTransaction($customer_id, $transaction_id)
    {

        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling customerTransaction');
        }
        // verify the required parameter 'transaction_id' is set
        if ($transaction_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $transaction_id when calling customerTransaction');
        }

        // parse inputs
        $resourcePath = "/customers/{customer_id}/transactions/{transaction_id}";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "GET";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());



        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customer_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }// path params
        if ($transaction_id !== null) {
            $resourcePath = str_replace(
                "{" . "transaction_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($transaction_id),
                $resourcePath
            );
        }



        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } else if (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }

        // make the API Call
        try
        {
            list($response, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams
            );

            return array($response, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }

    }

    /**
     * resellerBalance
     *
     * retrieve a sub reseller's balance
     *
     * @param int $reseller_id Reseller Id of the Reseller whose Available Balance is to be fetched (required)
     * @return void
     * @throws \Liquid\Client\ApiException on non-2xx response
     */
    public function resellerBalance($reseller_id)
    {

        // verify the required parameter 'reseller_id' is set
        if ($reseller_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $reseller_id when calling resellerBalance');
        }

        // parse inputs
        $resourcePath = "/resellers/{reseller_id}/balance";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "GET";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());



        // path params
        if ($reseller_id !== null) {
            $resourcePath = str_replace(
                "{" . "reseller_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($reseller_id),
                $resourcePath
            );
        }



        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } else if (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }

        // make the API Call
        try
        {
            list($response, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams
            );

            return array($response, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }

    }

    /**
     * allResellerTransaction
     *
     * list all transactions of a sub reseller
     *
     * @param int $reseller_id Reseller Id of the Reseller whose Transactions are to be fetched (required)
     * @param int $limit Limit number of Transactions to be fetched. This should be a value between 10 to 100. (optional)
     * @param int $page_no Page number for which details are to be fetched (optional)
     * @param string $transaction_type Type of the Transactions. Possible values can be domain, deposit, note, privacy_protect. (optional)
     * @param string $transaction_id Arrays of Transaction Ids : 1,2,3,4. (optional)
     * @param string $date_start UNIX TimeStamp for listing of Transactions whose Creation Date is greater than date_start. Value can be yyyy-mm-dd. (optional)
     * @param string $date_end UNIX TimeStamp for listing of Transactions whose Creation Date is less than date_end. Value can be yyyy-mm-dd. (optional)
     * @param int $amount_range_start Lowest amount in the range of Transactions you intend to list (optional)
     * @param int $amount_range_end Highest amount in the range of Transactions you intend to list (optional)
     * @param string $description Description (optional)
     * @param bool $only_pending_customer Show only pending customer transactions. can be filled with string true or false, 1 or 0 (optional)
     * @return void
     * @throws \Liquid\Client\ApiException on non-2xx response
     */
    public function allResellerTransaction($reseller_id, $limit=null, $page_no=null, $transaction_type=null, $transaction_id=null, $date_start=null, $date_end=null, $amount_range_start=null, $amount_range_end=null, $description=null, $only_pending_customer=null)
    {

        // verify the required parameter 'reseller_id' is set
        if ($reseller_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $reseller_id when calling allResellerTransaction');
        }

        // parse inputs
        $resourcePath = "/resellers/{reseller_id}/transactions";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "GET";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());

        // query params
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }// query params
        if ($page_no !== null) {
            $queryParams['page_no'] = $this->apiClient->getSerializer()->toQueryValue($page_no);
        }// query params
        if ($transaction_type !== null) {
            $queryParams['transaction_type'] = $this->apiClient->getSerializer()->toQueryValue($transaction_type);
        }// query params
        if ($transaction_id !== null) {
            $queryParams['transaction_id'] = $this->apiClient->getSerializer()->toQueryValue($transaction_id);
        }// query params
        if ($date_start !== null) {
            $queryParams['date_start'] = $this->apiClient->getSerializer()->toQueryValue($date_start);
        }// query params
        if ($date_end !== null) {
            $queryParams['date_end'] = $this->apiClient->getSerializer()->toQueryValue($date_end);
        }// query params
        if ($amount_range_start !== null) {
            $queryParams['amount_range_start'] = $this->apiClient->getSerializer()->toQueryValue($amount_range_start);
        }// query params
        if ($amount_range_end !== null) {
            $queryParams['amount_range_end'] = $this->apiClient->getSerializer()->toQueryValue($amount_range_end);
        }// query params
        if ($description !== null) {
            $queryParams['description'] = $this->apiClient->getSerializer()->toQueryValue($description);
        }// query params
        if ($only_pending_customer !== null) {
            $queryParams['only_pending_customer'] = $this->apiClient->getSerializer()->toQueryValue($only_pending_customer);
        }

        // path params
        if ($reseller_id !== null) {
            $resourcePath = str_replace(
                "{" . "reseller_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($reseller_id),
                $resourcePath
            );
        }



        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } else if (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }

        // make the API Call
        try
        {
            list($response, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams
            );

            return array($response, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }

    }

    /**
     * addFundReseller
     *
     * add fund to a sub reseller
     *
     * @param int $reseller_id Reseller Id of the Reseller in whose Debit Account these funds are to be added (required)
     * @param string $amount Amount to be added (required)
     * @param string $description Description for the Transaction (required)
     * @return void
     * @throws \Liquid\Client\ApiException on non-2xx response
     */
    public function addFundReseller($reseller_id, $amount, $description)
    {

        // verify the required parameter 'reseller_id' is set
        if ($reseller_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $reseller_id when calling addFundReseller');
        }
        // verify the required parameter 'amount' is set
        if ($amount === null) {
            throw new \InvalidArgumentException('Missing the required parameter $amount when calling addFundReseller');
        }
        // verify the required parameter 'description' is set
        if ($description === null) {
            throw new \InvalidArgumentException('Missing the required parameter $description when calling addFundReseller');
        }

        // parse inputs
        $resourcePath = "/resellers/{reseller_id}/transactions/fund";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "POST";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());



        // path params
        if ($reseller_id !== null) {
            $resourcePath = str_replace(
                "{" . "reseller_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($reseller_id),
                $resourcePath
            );
        }
        // form params
        if ($amount !== null) {
            $formParams['amount'] = $this->apiClient->getSerializer()->toFormValue($amount);
        }// form params
        if ($description !== null) {
            $formParams['description'] = $this->apiClient->getSerializer()->toFormValue($description);
        }


        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } else if (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }

        // make the API Call
        try
        {
            list($response, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams
            );

            return array($response, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }

    }

    /**
     * resellerTransaction
     *
     * retrieve a reseller's transaction
     *
     * @param int $reseller_id Reseller Id of the Reseller whose Transactions are to be fetched (required)
     * @param int $transaction_id Transaction Ids of the Transactions whose details are to be fetched (required)
     * @return void
     * @throws \Liquid\Client\ApiException on non-2xx response
     */
    public function resellerTransaction($reseller_id, $transaction_id)
    {

        // verify the required parameter 'reseller_id' is set
        if ($reseller_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $reseller_id when calling resellerTransaction');
        }
        // verify the required parameter 'transaction_id' is set
        if ($transaction_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $transaction_id when calling resellerTransaction');
        }

        // parse inputs
        $resourcePath = "/resellers/{reseller_id}/transactions/{transaction_id}";
        $resourcePath = str_replace("{format}", "json", $resourcePath);
        $method = "GET";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());



        // path params
        if ($reseller_id !== null) {
            $resourcePath = str_replace(
                "{" . "reseller_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($reseller_id),
                $resourcePath
            );
        }// path params
        if ($transaction_id !== null) {
            $resourcePath = str_replace(
                "{" . "transaction_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($transaction_id),
                $resourcePath
            );
        }



        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } else if (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }

        // make the API Call
        try
        {
            list($response, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, $method,
                $queryParams, $httpBody,
                $headerParams
            );

            return array($response, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }

    }

}
