<?php
/**
 * Customer
 *
 * PHP version 5
 *
 * @category Class
 * @package  Liquid\Client
 * @author   http://github.com/liquidregistrar/liquid-php
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/liquidregistrar/liquid-php
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the liquid code generator program.
 * https://github.com/liquidregistrar/liquid-php
 * Do not edit the class manually.
 */

namespace Liquid\Client\Model;

use \ArrayAccess;
/**
 * Customer Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Liquid\Client
 * @author      http://github.com/liquidregistrar/liquid-php
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/liquidregistrar/liquid-php
 */
class Customer implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $liquidTypes = array(
        'customer_id' => 'int',
        'reseller_id' => 'int',
        'status' => 'string',
        'email' => 'string',
        'name' => 'string',
        'company' => 'string',
        'creation_date' => 'string',
        'total_receipts' => 'string',
        'address_line_1' => 'string',
        'address_line_2' => 'string',
        'address_line_3' => 'string',
        'city' => 'string',
        'state' => 'string',
        'country_code' => 'string',
        'country_name' => 'string',
        'zipcode' => 'string',
        'tel_cc_no' => 'string',
        'tel_no' => 'string',
        'alt_tel_cc_no' => 'string',
        'alt_tel_no' => 'string',
        'mobile_cc_no' => 'string',
        'mobile_no' => 'string',
        'fax_cc_no' => 'string',
        'fax_no' => 'string',
        'lang_id' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'customer_id' => 'customer_id',
        'reseller_id' => 'reseller_id',
        'status' => 'status',
        'email' => 'email',
        'name' => 'name',
        'company' => 'company',
        'creation_date' => 'creation_date',
        'total_receipts' => 'total_receipts',
        'address_line_1' => 'address_line_1',
        'address_line_2' => 'address_line_2',
        'address_line_3' => 'address_line_3',
        'city' => 'city',
        'state' => 'state',
        'country_code' => 'country_code',
        'country_name' => 'country_name',
        'zipcode' => 'zipcode',
        'tel_cc_no' => 'tel_cc_no',
        'tel_no' => 'tel_no',
        'alt_tel_cc_no' => 'alt_tel_cc_no',
        'alt_tel_no' => 'alt_tel_no',
        'mobile_cc_no' => 'mobile_cc_no',
        'mobile_no' => 'mobile_no',
        'fax_cc_no' => 'fax_cc_no',
        'fax_no' => 'fax_no',
        'lang_id' => 'lang_id'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'customer_id' => 'setCustomerId',
        'reseller_id' => 'setResellerId',
        'status' => 'setStatus',
        'email' => 'setEmail',
        'name' => 'setName',
        'company' => 'setCompany',
        'creation_date' => 'setCreationDate',
        'total_receipts' => 'setTotalReceipts',
        'address_line_1' => 'setAddressLine1',
        'address_line_2' => 'setAddressLine2',
        'address_line_3' => 'setAddressLine3',
        'city' => 'setCity',
        'state' => 'setState',
        'country_code' => 'setCountryCode',
        'country_name' => 'setCountryName',
        'zipcode' => 'setZipcode',
        'tel_cc_no' => 'setTelCcNo',
        'tel_no' => 'setTelNo',
        'alt_tel_cc_no' => 'setAltTelCcNo',
        'alt_tel_no' => 'setAltTelNo',
        'mobile_cc_no' => 'setMobileCcNo',
        'mobile_no' => 'setMobileNo',
        'fax_cc_no' => 'setFaxCcNo',
        'fax_no' => 'setFaxNo',
        'lang_id' => 'setLangId'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'customer_id' => 'getCustomerId',
        'reseller_id' => 'getResellerId',
        'status' => 'getStatus',
        'email' => 'getEmail',
        'name' => 'getName',
        'company' => 'getCompany',
        'creation_date' => 'getCreationDate',
        'total_receipts' => 'getTotalReceipts',
        'address_line_1' => 'getAddressLine1',
        'address_line_2' => 'getAddressLine2',
        'address_line_3' => 'getAddressLine3',
        'city' => 'getCity',
        'state' => 'getState',
        'country_code' => 'getCountryCode',
        'country_name' => 'getCountryName',
        'zipcode' => 'getZipcode',
        'tel_cc_no' => 'getTelCcNo',
        'tel_no' => 'getTelNo',
        'alt_tel_cc_no' => 'getAltTelCcNo',
        'alt_tel_no' => 'getAltTelNo',
        'mobile_cc_no' => 'getMobileCcNo',
        'mobile_no' => 'getMobileNo',
        'fax_cc_no' => 'getFaxCcNo',
        'fax_no' => 'getFaxNo',
        'lang_id' => 'getLangId'
    );
  
    
    /**
      * $customer_id 
      * @var int
      */
    protected $customer_id;
    
    /**
      * $reseller_id 
      * @var int
      */
    protected $reseller_id;
    
    /**
      * $status 
      * @var string
      */
    protected $status;
    
    /**
      * $email customer status
      * @var string
      */
    protected $email;
    
    /**
      * $name 
      * @var string
      */
    protected $name;
    
    /**
      * $company 
      * @var string
      */
    protected $company;
    
    /**
      * $creation_date 
      * @var string
      */
    protected $creation_date;
    
    /**
      * $total_receipts 
      * @var string
      */
    protected $total_receipts;
    
    /**
      * $address_line_1 
      * @var string
      */
    protected $address_line_1;
    
    /**
      * $address_line_2 
      * @var string
      */
    protected $address_line_2;
    
    /**
      * $address_line_3 
      * @var string
      */
    protected $address_line_3;
    
    /**
      * $city 
      * @var string
      */
    protected $city;
    
    /**
      * $state 
      * @var string
      */
    protected $state;
    
    /**
      * $country_code 
      * @var string
      */
    protected $country_code;
    
    /**
      * $country_name 
      * @var string
      */
    protected $country_name;
    
    /**
      * $zipcode 
      * @var string
      */
    protected $zipcode;
    
    /**
      * $tel_cc_no 
      * @var string
      */
    protected $tel_cc_no;
    
    /**
      * $tel_no 
      * @var string
      */
    protected $tel_no;
    
    /**
      * $alt_tel_cc_no 
      * @var string
      */
    protected $alt_tel_cc_no;
    
    /**
      * $alt_tel_no 
      * @var string
      */
    protected $alt_tel_no;
    
    /**
      * $mobile_cc_no 
      * @var string
      */
    protected $mobile_cc_no;
    
    /**
      * $mobile_no 
      * @var string
      */
    protected $mobile_no;
    
    /**
      * $fax_cc_no 
      * @var string
      */
    protected $fax_cc_no;
    
    /**
      * $fax_no 
      * @var string
      */
    protected $fax_no;
    
    /**
      * $lang_id 
      * @var string
      */
    protected $lang_id;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->customer_id = $data["customer_id"];
            $this->reseller_id = $data["reseller_id"];
            $this->status = $data["status"];
            $this->email = $data["email"];
            $this->name = $data["name"];
            $this->company = $data["company"];
            $this->creation_date = $data["creation_date"];
            $this->total_receipts = $data["total_receipts"];
            $this->address_line_1 = $data["address_line_1"];
            $this->address_line_2 = $data["address_line_2"];
            $this->address_line_3 = $data["address_line_3"];
            $this->city = $data["city"];
            $this->state = $data["state"];
            $this->country_code = $data["country_code"];
            $this->country_name = $data["country_name"];
            $this->zipcode = $data["zipcode"];
            $this->tel_cc_no = $data["tel_cc_no"];
            $this->tel_no = $data["tel_no"];
            $this->alt_tel_cc_no = $data["alt_tel_cc_no"];
            $this->alt_tel_no = $data["alt_tel_no"];
            $this->mobile_cc_no = $data["mobile_cc_no"];
            $this->mobile_no = $data["mobile_no"];
            $this->fax_cc_no = $data["fax_cc_no"];
            $this->fax_no = $data["fax_no"];
            $this->lang_id = $data["lang_id"];
        }
    }
    
    /**
     * Gets customer_id
     * @return int
     */
    public function getCustomerId()
    {
        return $this->customer_id;
    }
  
    /**
     * Sets customer_id
     * @param int $customer_id 
     * @return $this
     */
    public function setCustomerId($customer_id)
    {
        
        $this->customer_id = $customer_id;
        return $this;
    }
    
    /**
     * Gets reseller_id
     * @return int
     */
    public function getResellerId()
    {
        return $this->reseller_id;
    }
  
    /**
     * Sets reseller_id
     * @param int $reseller_id 
     * @return $this
     */
    public function setResellerId($reseller_id)
    {
        
        $this->reseller_id = $reseller_id;
        return $this;
    }
    
    /**
     * Gets status
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }
  
    /**
     * Sets status
     * @param string $status 
     * @return $this
     */
    public function setStatus($status)
    {
        
        $this->status = $status;
        return $this;
    }
    
    /**
     * Gets email
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }
  
    /**
     * Sets email
     * @param string $email customer status
     * @return $this
     */
    public function setEmail($email)
    {
        $allowed_values = array("Active", "Suspended", "Deleted", "Execute Queue", "Failed");
        if (!in_array($email, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'email', must be one of 'Active', 'Suspended', 'Deleted', 'Execute Queue', 'Failed'");
        }
        $this->email = $email;
        return $this;
    }
    
    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
  
    /**
     * Sets name
     * @param string $name 
     * @return $this
     */
    public function setName($name)
    {
        
        $this->name = $name;
        return $this;
    }
    
    /**
     * Gets company
     * @return string
     */
    public function getCompany()
    {
        return $this->company;
    }
  
    /**
     * Sets company
     * @param string $company 
     * @return $this
     */
    public function setCompany($company)
    {
        
        $this->company = $company;
        return $this;
    }
    
    /**
     * Gets creation_date
     * @return string
     */
    public function getCreationDate()
    {
        return $this->creation_date;
    }
  
    /**
     * Sets creation_date
     * @param string $creation_date 
     * @return $this
     */
    public function setCreationDate($creation_date)
    {
        
        $this->creation_date = $creation_date;
        return $this;
    }
    
    /**
     * Gets total_receipts
     * @return string
     */
    public function getTotalReceipts()
    {
        return $this->total_receipts;
    }
  
    /**
     * Sets total_receipts
     * @param string $total_receipts 
     * @return $this
     */
    public function setTotalReceipts($total_receipts)
    {
        
        $this->total_receipts = $total_receipts;
        return $this;
    }
    
    /**
     * Gets address_line_1
     * @return string
     */
    public function getAddressLine1()
    {
        return $this->address_line_1;
    }
  
    /**
     * Sets address_line_1
     * @param string $address_line_1 
     * @return $this
     */
    public function setAddressLine1($address_line_1)
    {
        
        $this->address_line_1 = $address_line_1;
        return $this;
    }
    
    /**
     * Gets address_line_2
     * @return string
     */
    public function getAddressLine2()
    {
        return $this->address_line_2;
    }
  
    /**
     * Sets address_line_2
     * @param string $address_line_2 
     * @return $this
     */
    public function setAddressLine2($address_line_2)
    {
        
        $this->address_line_2 = $address_line_2;
        return $this;
    }
    
    /**
     * Gets address_line_3
     * @return string
     */
    public function getAddressLine3()
    {
        return $this->address_line_3;
    }
  
    /**
     * Sets address_line_3
     * @param string $address_line_3 
     * @return $this
     */
    public function setAddressLine3($address_line_3)
    {
        
        $this->address_line_3 = $address_line_3;
        return $this;
    }
    
    /**
     * Gets city
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }
  
    /**
     * Sets city
     * @param string $city 
     * @return $this
     */
    public function setCity($city)
    {
        
        $this->city = $city;
        return $this;
    }
    
    /**
     * Gets state
     * @return string
     */
    public function getState()
    {
        return $this->state;
    }
  
    /**
     * Sets state
     * @param string $state 
     * @return $this
     */
    public function setState($state)
    {
        
        $this->state = $state;
        return $this;
    }
    
    /**
     * Gets country_code
     * @return string
     */
    public function getCountryCode()
    {
        return $this->country_code;
    }
  
    /**
     * Sets country_code
     * @param string $country_code 
     * @return $this
     */
    public function setCountryCode($country_code)
    {
        
        $this->country_code = $country_code;
        return $this;
    }
    
    /**
     * Gets country_name
     * @return string
     */
    public function getCountryName()
    {
        return $this->country_name;
    }
  
    /**
     * Sets country_name
     * @param string $country_name 
     * @return $this
     */
    public function setCountryName($country_name)
    {
        
        $this->country_name = $country_name;
        return $this;
    }
    
    /**
     * Gets zipcode
     * @return string
     */
    public function getZipcode()
    {
        return $this->zipcode;
    }
  
    /**
     * Sets zipcode
     * @param string $zipcode 
     * @return $this
     */
    public function setZipcode($zipcode)
    {
        
        $this->zipcode = $zipcode;
        return $this;
    }
    
    /**
     * Gets tel_cc_no
     * @return string
     */
    public function getTelCcNo()
    {
        return $this->tel_cc_no;
    }
  
    /**
     * Sets tel_cc_no
     * @param string $tel_cc_no 
     * @return $this
     */
    public function setTelCcNo($tel_cc_no)
    {
        
        $this->tel_cc_no = $tel_cc_no;
        return $this;
    }
    
    /**
     * Gets tel_no
     * @return string
     */
    public function getTelNo()
    {
        return $this->tel_no;
    }
  
    /**
     * Sets tel_no
     * @param string $tel_no 
     * @return $this
     */
    public function setTelNo($tel_no)
    {
        
        $this->tel_no = $tel_no;
        return $this;
    }
    
    /**
     * Gets alt_tel_cc_no
     * @return string
     */
    public function getAltTelCcNo()
    {
        return $this->alt_tel_cc_no;
    }
  
    /**
     * Sets alt_tel_cc_no
     * @param string $alt_tel_cc_no 
     * @return $this
     */
    public function setAltTelCcNo($alt_tel_cc_no)
    {
        
        $this->alt_tel_cc_no = $alt_tel_cc_no;
        return $this;
    }
    
    /**
     * Gets alt_tel_no
     * @return string
     */
    public function getAltTelNo()
    {
        return $this->alt_tel_no;
    }
  
    /**
     * Sets alt_tel_no
     * @param string $alt_tel_no 
     * @return $this
     */
    public function setAltTelNo($alt_tel_no)
    {
        
        $this->alt_tel_no = $alt_tel_no;
        return $this;
    }
    
    /**
     * Gets mobile_cc_no
     * @return string
     */
    public function getMobileCcNo()
    {
        return $this->mobile_cc_no;
    }
  
    /**
     * Sets mobile_cc_no
     * @param string $mobile_cc_no 
     * @return $this
     */
    public function setMobileCcNo($mobile_cc_no)
    {
        
        $this->mobile_cc_no = $mobile_cc_no;
        return $this;
    }
    
    /**
     * Gets mobile_no
     * @return string
     */
    public function getMobileNo()
    {
        return $this->mobile_no;
    }
  
    /**
     * Sets mobile_no
     * @param string $mobile_no 
     * @return $this
     */
    public function setMobileNo($mobile_no)
    {
        
        $this->mobile_no = $mobile_no;
        return $this;
    }
    
    /**
     * Gets fax_cc_no
     * @return string
     */
    public function getFaxCcNo()
    {
        return $this->fax_cc_no;
    }
  
    /**
     * Sets fax_cc_no
     * @param string $fax_cc_no 
     * @return $this
     */
    public function setFaxCcNo($fax_cc_no)
    {
        
        $this->fax_cc_no = $fax_cc_no;
        return $this;
    }
    
    /**
     * Gets fax_no
     * @return string
     */
    public function getFaxNo()
    {
        return $this->fax_no;
    }
  
    /**
     * Sets fax_no
     * @param string $fax_no 
     * @return $this
     */
    public function setFaxNo($fax_no)
    {
        
        $this->fax_no = $fax_no;
        return $this;
    }
    
    /**
     * Gets lang_id
     * @return string
     */
    public function getLangId()
    {
        return $this->lang_id;
    }
  
    /**
     * Sets lang_id
     * @param string $lang_id 
     * @return $this
     */
    public function setLangId($lang_id)
    {
        
        $this->lang_id = $lang_id;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
